@startuml GoalBotArchitecture

interface user as "User"

node "Frontend" {
  [ui] as "User Interface"
}

node "Backend" {
  ' controllers
  node "Controllers" {
    [api] as "API"
  }
  ' directors
  node "Directors" {
    [director] as "Director"
  }
  ' supervisors
  node "Supervisors" {
    [supervisor] as "TBC"
  }
  note left of [supervisor]
    Initial MVP will have no supervisors
    Consider this as pass-through
  end note
  ' agents
  node "Agents" {
    [goals] as "Goal Agent"
    [summariser] as "Summariser"
    [nextBestQuestion] as "Next Best Question"
  }
  ' tools
  node "Tools" {
    [graphUtils] as "Graph DB utils"
  }
}

cloud {
  [llm] as "Mistral LLM"
}

database "Graph Database" {
  frame "neo4j" {
    [Nodes+Relationships] as data
  }
}

' flows
user -->  ui
ui --> api
api --> director
director ..> supervisor
director ..> llm
supervisor --> goals
supervisor --> nextBestQuestion
supervisor --> summariser
goals --> graphUtils
graphUtils --> data

@enduml